name: "🐛 Bug report"
labels: ["type/bug","prio/triage"]
body:
  - type: textarea
    id: desc
    attributes: { label: What happened?, description: Include expected vs actual. }
    validations: { required: true }
  - type: dropdown
    id: os
    attributes: { label: Windows Server version, options: ["2019","2022"] }
  - type: input
    id: commit
    attributes: { label: Toolkit version / commit }
  - type: textarea
    id: repro
    attributes: { label: Repro steps }
  - type: textarea
    id: logs
    attributes: { label: Relevant logs (-WhatIf or run), render: shell }
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submit checks
      options:
        - label: Searched existing issues/discussions
          required: true
        - label: Reproduced with `-WhatIf` and captured logs
          required: true
