name: CI - Pester & PSSA

on:
  pull_request:
    paths:
      - '**/*.ps1'
      - 'lib/**'
      - 'scripts/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
      - name: Install Pester
        run: pwsh -Command "Install-Module -Name Pester -Force -Scope CurrentUser"
      - name: Install PSScriptAnalyzer
        run: pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser"
      - name: Run PSScriptAnalyzer
        run: pwsh -Command "Invoke-ScriptAnalyzer -Path . -Recurse"
      - name: Run Pester
        run: pwsh -Command "Invoke-Pester -Script . -EnableExit"
